export const weatherIcons = {
    0: 'wi wi-day-sunny',
    1: 'wi wi-day-cloudy',
    2: 'wi wi-cloud',
    3: 'wi wi-cloudy',
    45: 'wi wi-fog',
    48: 'wi wi-fog',
    51: 'wi wi-sprinkle',
    53: 'wi wi-sprinkle',
    55: 'wi wi-showers',
    61: 'wi wi-rain',
    63: 'wi wi-rain',
    65: 'wi wi-rain',
    66: 'wi wi-rain-mix',
    67: 'wi wi-rain-mix',
    71: 'wi wi-snow',
    73: 'wi wi-snow',
    75: 'wi wi-snow',
    80: 'wi wi-showers',
    81: 'wi wi-thunderstorm',
    82: 'wi wi-thunderstorm',
    95: 'wi wi-thunderstorm',
    96: 'wi wi-thunderstorm',
    99: 'wi wi-thunderstorm',
};
