export const weatherIcons = {
    0: 'wi wi-day-sunny',
    1: 'wi wi-day-cloudy',
    2: 'wi wi-cloud',
    3: 'wi wi-cloudy',
    45: 'wi wi-fog',
    48: 'wi wi-fog',
    51: 'wi wi-sprinkle',
    53: 'wi wi-sprinkle',
    55: 'wi wi-showers',
    61: 'wi wi-rain',
    63: 'wi wi-rain',
    65: 'wi wi-rain',
    66: 'wi wi-rain-mix',
    67: 'wi wi-rain-mix',
    71: 'wi wi-snow',
    73: 'wi wi-snow',
    75: 'wi wi-snow',
    80: 'wi wi-showers',
    81: 'wi wi-thunderstorm',
    82: 'wi wi-thunderstorm',
    95: 'wi wi-thunderstorm',
    96: 'wi wi-thunderstorm',
    99: 'wi wi-thunderstorm',
};

export const slogans = {
    0: 'Clear skies, clear mind!',
    1: 'If the goose honks high, fair weather. If the goose honks low, foul weather.',
    2: 'Overcast skies, but the day is still yours to seize!',
    3: 'When wooden chairs creak, rain will come within a week.',
    45: 'Fog in the morning, travelers take warning.',
    48: 'Lost in the mist, but found in the moment.',
    51: 'A sprinkle of rain, a sprinkle of magic.',
    53: 'Gentle showers for gentle thoughts.',
    55: 'Rain before seven, fine by eleven.',
    61: 'Rainy days are perfect for dreaming big.',
    63: 'Let the rain wash away the stress.',
    65: 'Raindrops keep falling, and so should your worries.',
    66: 'Rain mixed with snow, nature\’s perfect duo.',
    67: 'When pipes smell stronger, it\’s going to rain.',
    71: 'Snowflakes are kisses from the sky.',
    73: 'When the wind whistles through the trees, snow is on its way.',
    75: 'Blankets of snow, blankets of joy.',
    80: 'April showers bring May flowers.',
    81: 'Thunderstorms: nature\’s drumroll.',
    82: 'Feel the power of the storm!',
    95: 'Red sky at night, sailor\’s delight.',
    96: 'When the sky growls, listen to its story.',
    99: 'Electric skies, electric vibes!'
};